"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Vehicle = { id: string; make: string; model: string; variant: string | null; year: number; mileage: number; price: number; currency: string; transmission: string | null; fuel: string | null; drivetrain: string | null; bodyStyle: string | null; equipment: string[] };
const fields: { key: keyof Vehicle; label: string }[] = [{ key: "price", label: "Precio" }, { key: "year", label: "Año" }, { key: "mileage", label: "Kilometraje" }, { key: "transmission", label: "Transmisión" }, { key: "fuel", label: "Combustible" }, { key: "drivetrain", label: "Tracción" }, { key: "bodyStyle", label: "Carrocería" }, { key: "equipment", label: "Equipamiento" }];
export default function ComparePage() {
  const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [error, setError] = useState("");
  useEffect(() => { const ids = new URLSearchParams(window.location.search).get("ids")?.split(",").filter(Boolean) ?? []; if (ids.length < 2) { setError("Selecciona al menos dos vehículos publicados para comparar."); return; } void fetch(`/api/proxy/public/vehicles/compare?${ids.map((id) => `ids=${encodeURIComponent(id)}`).join("&")}`).then(async r => r.ok ? setVehicles(await r.json() as Vehicle[]) : setError("No fue posible cargar la comparación.")); }, []);
  if (error) return <section className="mx-auto max-w-5xl py-12"><h1 className="text-3xl font-bold">Comparar vehículos</h1><p className="mt-4 text-slate-700">{error}</p><Link className="mt-6 inline-block font-semibold text-brand underline" href="/catalogo">Volver al catálogo</Link></section>;
  return <section className="mx-auto max-w-6xl py-10"><h1 className="text-3xl font-bold text-slate-900">Comparar vehículos</h1><div className="mt-6 overflow-x-auto"><table className="min-w-full border-collapse text-sm"><thead><tr><th className="sticky left-0 bg-white p-3 text-left">Característica</th>{vehicles.map(v => <th key={v.id} className="min-w-56 border-b p-3 text-left"><Link href={`/vehiculos/${v.id}`} className="text-brand underline">{v.make} {v.model} {v.variant ?? ""}</Link></th>)}</tr></thead><tbody>{fields.map(field => <tr key={field.key} className="border-b"><th className="sticky left-0 bg-white p-3 text-left font-semibold">{field.label}</th>{vehicles.map(v => <td key={v.id} className="p-3">{Array.isArray(v[field.key]) ? (v[field.key] as string[]).join(", ") || "No especificado" : field.key === "price" ? new Intl.NumberFormat("es-MX", { style: "currency", currency: v.currency, maximumFractionDigits: 0 }).format(v.price) : String(v[field.key] ?? "No especificado")}</td>)}</tr>)}</tbody></table></div></section>;
}
