/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v{version}/admin/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/admin/sessions/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginCommand"];
                    "text/json": components["schemas"]["LoginCommand"];
                    "application/*+json": components["schemas"]["LoginCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TokenResult"];
                        "application/json": components["schemas"]["TokenResult"];
                        "text/json": components["schemas"]["TokenResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                    "text/json": components["schemas"]["RefreshRequest"];
                    "application/*+json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TokenResult"];
                        "application/json": components["schemas"]["TokenResult"];
                        "text/json": components["schemas"]["TokenResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                    "text/json": components["schemas"]["RefreshRequest"];
                    "application/*+json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Branch"];
                    "text/json": components["schemas"]["Branch"];
                    "application/*+json": components["schemas"]["Branch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Branch"];
                        "application/json": components["schemas"]["Branch"];
                        "text/json": components["schemas"]["Branch"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/makes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Make"];
                    "text/json": components["schemas"]["Make"];
                    "application/*+json": components["schemas"]["Make"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Make"];
                        "application/json": components["schemas"]["Make"];
                        "text/json": components["schemas"]["Make"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/makes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Make"];
                    "text/json": components["schemas"]["Make"];
                    "application/*+json": components["schemas"]["Make"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    makeId?: string;
                };
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Model"];
                    "text/json": components["schemas"]["Model"];
                    "application/*+json": components["schemas"]["Model"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Model"];
                        "application/json": components["schemas"]["Model"];
                        "text/json": components["schemas"]["Model"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Model"];
                    "text/json": components["schemas"]["Model"];
                    "application/*+json": components["schemas"]["Model"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    modelId?: string;
                };
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Variant"];
                    "text/json": components["schemas"]["Variant"];
                    "application/*+json": components["schemas"]["Variant"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Variant"];
                        "application/json": components["schemas"]["Variant"];
                        "text/json": components["schemas"]["Variant"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/variants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Variant"];
                    "text/json": components["schemas"]["Variant"];
                    "application/*+json": components["schemas"]["Variant"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Equipment"];
                    "text/json": components["schemas"]["Equipment"];
                    "application/*+json": components["schemas"]["Equipment"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Equipment"];
                        "application/json": components["schemas"]["Equipment"];
                        "text/json": components["schemas"]["Equipment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/equipment/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Equipment"];
                    "text/json": components["schemas"]["Equipment"];
                    "application/*+json": components["schemas"]["Equipment"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/technical-catalogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    category?: string;
                };
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TechnicalCatalog"];
                    "text/json": components["schemas"]["TechnicalCatalog"];
                    "application/*+json": components["schemas"]["TechnicalCatalog"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TechnicalCatalog"];
                        "application/json": components["schemas"]["TechnicalCatalog"];
                        "text/json": components["schemas"]["TechnicalCatalog"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/technical-catalogs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TechnicalCatalog"];
                    "text/json": components["schemas"]["TechnicalCatalog"];
                    "application/*+json": components["schemas"]["TechnicalCatalog"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CustomFieldDefinition"];
                    "text/json": components["schemas"]["CustomFieldDefinition"];
                    "application/*+json": components["schemas"]["CustomFieldDefinition"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomFieldDefinition"];
                        "application/json": components["schemas"]["CustomFieldDefinition"];
                        "text/json": components["schemas"]["CustomFieldDefinition"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/fields/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    MakeId?: string;
                    ModelId?: string;
                    BranchId?: string;
                    Status?: "Draft" | "InReview" | "Photography" | "Inspection" | "Approved" | "Published" | "Reserved" | "Sold" | "Delivered" | "Withdrawn";
                    MinYear?: number;
                    MaxPrice?: number;
                    Search?: string;
                    Sort?: string;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VehicleResponsePagedResult"];
                        "application/json": components["schemas"]["VehicleResponsePagedResult"];
                        "text/json": components["schemas"]["VehicleResponsePagedResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VehicleRequest"];
                    "text/json": components["schemas"]["VehicleRequest"];
                    "application/*+json": components["schemas"]["VehicleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VehicleResponse"];
                        "application/json": components["schemas"]["VehicleResponse"];
                        "text/json": components["schemas"]["VehicleResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VehicleResponse"];
                        "application/json": components["schemas"]["VehicleResponse"];
                        "text/json": components["schemas"]["VehicleResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match"?: string;
                };
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VehicleRequest"];
                    "text/json": components["schemas"]["VehicleRequest"];
                    "application/*+json": components["schemas"]["VehicleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VehicleResponse"];
                        "application/json": components["schemas"]["VehicleResponse"];
                        "text/json": components["schemas"]["VehicleResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/vehicles/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TransitionRequest"];
                    "text/json": components["schemas"]["TransitionRequest"];
                    "application/*+json": components["schemas"]["TransitionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VehicleResponse"];
                        "application/json": components["schemas"]["VehicleResponse"];
                        "text/json": components["schemas"]["VehicleResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/inventory/vehicles/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/public/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Q?: string;
                    MakeId?: string;
                    ModelId?: string;
                    VariantId?: string;
                    BranchId?: string;
                    MinYear?: number;
                    MaxYear?: number;
                    MinPrice?: number;
                    MaxPrice?: number;
                    MaxMileage?: number;
                    Condition?: "New" | "Used";
                    Transmission?: string;
                    Fuel?: string;
                    Drivetrain?: string;
                    BodyStyle?: string;
                    Sort?: string;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicVehicleListItemDtoPublicPagedResult"];
                        "application/json": components["schemas"]["PublicVehicleListItemDtoPublicPagedResult"];
                        "text/json": components["schemas"]["PublicVehicleListItemDtoPublicPagedResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/public/vehicles/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicFilterOptionsDto"];
                        "application/json": components["schemas"]["PublicFilterOptionsDto"];
                        "text/json": components["schemas"]["PublicFilterOptionsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/public/vehicles/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicVehicleListItemDto"][];
                        "application/json": components["schemas"]["PublicVehicleListItemDto"][];
                        "text/json": components["schemas"]["PublicVehicleListItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/public/vehicles/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicVehicleListItemDto"][];
                        "application/json": components["schemas"]["PublicVehicleListItemDto"][];
                        "text/json": components["schemas"]["PublicVehicleListItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/public/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicVehicleDetailDto"];
                        "application/json": components["schemas"]["PublicVehicleDetailDto"];
                        "text/json": components["schemas"]["PublicVehicleDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/public/vehicles/{id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicVehicleListItemDto"][];
                        "application/json": components["schemas"]["PublicVehicleListItemDto"][];
                        "text/json": components["schemas"]["PublicVehicleListItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/public/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicBranchDto"][];
                        "application/json": components["schemas"]["PublicBranchDto"][];
                        "text/json": components["schemas"]["PublicBranchDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Branch: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            address?: string | null;
            phones?: string | null;
            hours?: string | null;
            managerName?: string | null;
            isActive?: boolean;
        };
        CustomFieldDefinition: {
            /** Format: uuid */
            id?: string;
            key?: string | null;
            label?: string | null;
            type?: components["schemas"]["CustomFieldType"];
            isRequired?: boolean;
            vehicleType?: string | null;
            options?: string | null;
            isActive?: boolean;
            isPublic?: boolean;
            isFilterable?: boolean;
        };
        /** @enum {string} */
        CustomFieldType: "Text" | "Number" | "Boolean" | "Select" | "Date";
        Equipment: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            isDeleted?: boolean;
        };
        LoginCommand: {
            email?: string | null;
            password?: string | null;
        };
        Make: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            isDeleted?: boolean;
            readonly models?: components["schemas"]["Model"][] | null;
        };
        Model: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            isDeleted?: boolean;
            /** Format: uuid */
            makeId?: string;
            make?: components["schemas"]["Make"];
            readonly variants?: components["schemas"]["Variant"][] | null;
        };
        PublicBranchDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            address?: string | null;
            phones?: string[] | null;
            hours?: {
                [key: string]: string;
            } | null;
        };
        PublicBranchOptionDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
        };
        PublicCustomFieldFilterDto: {
            key?: string | null;
            label?: string | null;
            type?: components["schemas"]["CustomFieldType"];
            values?: string[] | null;
        };
        PublicFilterOptionsDto: {
            makes?: components["schemas"]["PublicMakeOptionDto"][] | null;
            branches?: components["schemas"]["PublicBranchOptionDto"][] | null;
            transmissions?: string[] | null;
            fuels?: string[] | null;
            bodyStyles?: string[] | null;
            drivetrains?: string[] | null;
            /** Format: double */
            minPrice?: number;
            /** Format: double */
            maxPrice?: number;
            /** Format: int32 */
            minYear?: number;
            /** Format: int32 */
            maxYear?: number;
            /** Format: int32 */
            minMileage?: number;
            /** Format: int32 */
            maxMileage?: number;
            conditions?: ("New" | "Used")[] | null;
            customFields?: components["schemas"]["PublicCustomFieldFilterDto"][] | null;
        };
        PublicMakeOptionDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            models?: components["schemas"]["PublicModelOptionDto"][] | null;
        };
        PublicModelOptionDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            variants?: components["schemas"]["PublicVariantOptionDto"][] | null;
        };
        PublicVariantOptionDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
        };
        PublicVehicleBranchDto: {
            name?: string | null;
            address?: string | null;
            phones?: string[] | null;
            hours?: {
                [key: string]: string;
            } | null;
        };
        PublicVehicleDetailDto: {
            /** Format: uuid */
            id?: string;
            make?: string | null;
            model?: string | null;
            variant?: string | null;
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            mileage?: number;
            /** Format: double */
            price?: number;
            currency?: string | null;
            /** @enum {string} */
            condition?: "New" | "Used";
            color?: string | null;
            transmission?: string | null;
            fuel?: string | null;
            drivetrain?: string | null;
            bodyStyle?: string | null;
            branch?: components["schemas"]["PublicVehicleBranchDto"];
            equipment?: string[] | null;
            customFields?: string | null;
            /** Format: date */
            publishedOn?: string | null;
            images?: components["schemas"]["PublicVehicleImageDto"][] | null;
        };
        PublicVehicleImageDto: {
            url?: string | null;
            alt?: string | null;
            /** Format: int32 */
            position?: number;
        };
        PublicVehicleListItemDto: {
            /** Format: uuid */
            id?: string;
            make?: string | null;
            model?: string | null;
            variant?: string | null;
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            mileage?: number;
            /** Format: double */
            price?: number;
            currency?: string | null;
            /** @enum {string} */
            condition?: "New" | "Used";
            color?: string | null;
            transmission?: string | null;
            fuel?: string | null;
            drivetrain?: string | null;
            bodyStyle?: string | null;
            branch?: string | null;
            /** Format: uuid */
            branchId?: string;
            imageUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        PublicVehicleListItemDtoPublicPagedResult: {
            items?: components["schemas"]["PublicVehicleListItemDto"][] | null;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        RefreshRequest: {
            refreshToken?: string | null;
        };
        TechnicalCatalog: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            isDeleted?: boolean;
            category?: string | null;
        };
        TokenResult: {
            accessToken?: string | null;
            refreshToken?: string | null;
            /** Format: date-time */
            accessTokenExpiresAt?: string;
        };
        TransitionRequest: {
            /** @enum {string} */
            toStatus?: "Draft" | "InReview" | "Photography" | "Inspection" | "Approved" | "Published" | "Reserved" | "Sold" | "Delivered" | "Withdrawn";
            reason?: string | null;
        };
        Variant: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            isDeleted?: boolean;
            /** Format: uuid */
            modelId?: string;
            model?: components["schemas"]["Model"];
        };
        VehicleRequest: {
            /** Format: uuid */
            makeId?: string;
            /** Format: uuid */
            modelId?: string;
            /** Format: uuid */
            variantId?: string | null;
            /** Format: uuid */
            branchId?: string;
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            mileage?: number;
            /** Format: double */
            price?: number;
            currency?: string | null;
            /** @enum {string} */
            condition?: "New" | "Used";
            vin?: string | null;
            plate?: string | null;
            color?: string | null;
            transmission?: string | null;
            fuel?: string | null;
            drivetrain?: string | null;
            bodyStyle?: string | null;
            customFields?: string | null;
            priceReason?: string | null;
        };
        VehicleResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            makeId?: string;
            /** Format: uuid */
            modelId?: string;
            /** Format: uuid */
            variantId?: string | null;
            /** Format: uuid */
            branchId?: string;
            make?: string | null;
            model?: string | null;
            variant?: string | null;
            branch?: string | null;
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            mileage?: number;
            /** Format: double */
            price?: number;
            currency?: string | null;
            /** @enum {string} */
            status?: "Draft" | "InReview" | "Photography" | "Inspection" | "Approved" | "Published" | "Reserved" | "Sold" | "Delivered" | "Withdrawn";
            /** @enum {string} */
            condition?: "New" | "Used";
            color?: string | null;
            transmission?: string | null;
            fuel?: string | null;
            drivetrain?: string | null;
            bodyStyle?: string | null;
            customFields?: string | null;
            /** Format: int32 */
            version?: number;
            vin?: string | null;
            plate?: string | null;
        };
        VehicleResponsePagedResult: {
            items?: components["schemas"]["VehicleResponse"][] | null;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
